### ISSUE TITLE
no glibc release

### ISSUE THREAD

**Issue by cromega** [dpb587/ssoca#5]
While it's not a massive issue in this day and age, I can run ssoca in a container with alpine, it would certainly be great to have a linux amd64 binary release with glibc linkage.

**Comment by dpb587** [comment]
Hi - I’m not an expert on linux/glibc linking and build options. Can you remind me what this means, or link me to a golang doc or another project’s build steps so I can learn a bit more?

**Comment by cromega** [comment]
Hi,

Sorry, I should have been a bit more verbose. Your build container is based on alpine linux, which uses musl libc, which means that the built binary is going to be linked against the musl interpreter. Most of the widely used distros, however, still use glibc by default. The result is that I can't execute the binary without jumping through some hoops. If you build the binary in a container based on ubuntu,for example, it will run just fine on most distros. If you want to be super-nice to us Linux peeps, you can release both a musl and a glibc build :)
